### PR TITLE
kozubenko 203 pz 2-3

### PR DESCRIPTION
**Pull request by Denis-Kozub**

### CODE REVIEW

**Comment by Zadvornyi** [comment]
Need to fix task 2. You should change label too

**Comment by Zadvornyi** [comment]
Screenshot 2023-10-16 at 21 23 25

**Comment by Zadvornyi** [comment]
Screenshot 2023-10-16 at 21 25 21

**Comment by Denis-Kozub** [comment]
FIx(label change too)

**Pull request closed without merging**
